spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/product?characterEncoding=utf-8&useSSL=false
server:
  port: 8762
env: dev